system: You are a very knowledgeable AI Assistant that will faithfully assist the user with their task.

introduction: You are asked to come up with a diverse context for - {task_description}.
principles: |
  Please follow these guiding principles when generating responses:
  * Use proper grammar and punctuation.
  * Always generate safe and respectful content. Do not generate content that is harmful, abusive, or offensive.
  * Always generate content that is factually accurate and relevant to the prompt.
  * Strictly adhere to the prompt and generate responses in the same style and format as the example.
  * Return the context between [Start of Context] and [End of Context] tags.
examples: |
  To better assist you with this task, here is an example of a context:
  [Start of Context]
  {seed_context}
  [End of Context]

generation: |
  Now generate a context paragraph, remember to follow the principles mentioned above and use the same format as the examples. Remember to use the same style and format as the example above. Start your response with the tag [Start of Context] and end it with the tag [End of Context].

start_tags: ["[Start of Context]"]
end_tags: ["[End of Context]"]
